// <auto-generated />
using System;
using Gimnasio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gimnasio.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260325031226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gimnasio.Entities.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AsistenciaId"));

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasColumnType("timestamp(0) without time zone");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("timestamp(0) without time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("RegistradaPorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("RegistradaPorUserId");

                    b.HasIndex("SocioId", "FechaHoraEntrada")
                        .HasDatabaseName("IX_Asistencias_Socio_Fecha");

                    b.ToTable("Asistencias", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EjercicioId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("GrupoMuscular")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("EjercicioId");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Ejercicios_Nombre");

                    b.ToTable("Ejercicios", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.Entrenador", b =>
                {
                    b.Property<int>("EntrenadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntrenadorId"));

                    b.Property<string>("Certificaciones")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EntrenadorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Entrenadores", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.Membresia", b =>
                {
                    b.Property<int>("MembresiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembresiaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("integer");

                    b.Property<bool>("EsRenovable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MembresiaId");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Membresias_Nombre");

                    b.ToTable("Membresias", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_NormalizedName");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RutinaId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("RutinaId");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("SocioId", "Activa")
                        .HasDatabaseName("IX_Rutinas_Socio_Activa");

                    b.ToTable("Rutinas", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.RutinaEjercicio", b =>
                {
                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer");

                    b.Property<int?>("DescansoSegundos")
                        .HasColumnType("integer");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoObjetivoKg")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int?>("Series")
                        .HasColumnType("integer");

                    b.HasKey("RutinaId", "EjercicioId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId", "Orden")
                        .HasDatabaseName("IX_RutinaEjercicios_Rutina_Orden");

                    b.ToTable("RutinaEjercicios", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.Socio", b =>
                {
                    b.Property<int>("SocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SocioId"));

                    b.Property<decimal?>("AlturaCm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("EmergenciaNombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmergenciaTelefono")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SocioId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Socios", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.SocioEntrenador", b =>
                {
                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.HasKey("SocioId", "EntrenadorId");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("SocioEntrenador", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.SocioMembresia", b =>
                {
                    b.Property<int>("SocioMembresiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SocioMembresiaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("SocioMembresiaId");

                    b.HasIndex("MembresiaId");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("IX_SocioMembresia_Socio");

                    b.HasIndex("Estado", "FechaFin")
                        .HasDatabaseName("IX_SocioMembresia_Estado_FechaFin");

                    b.ToTable("SocioMembresia", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp(0) without time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_NormalizedUserName");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_UserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Gimnasio.Entities.Asistencia", b =>
                {
                    b.HasOne("Gimnasio.Entities.User", "RegistradaPorUser")
                        .WithMany("AsistenciasRegistradas")
                        .HasForeignKey("RegistradaPorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gimnasio.Entities.Socio", "Socio")
                        .WithMany("Asistencias")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistradaPorUser");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Gimnasio.Entities.Entrenador", b =>
                {
                    b.HasOne("Gimnasio.Entities.User", "User")
                        .WithOne("Entrenador")
                        .HasForeignKey("Gimnasio.Entities.Entrenador", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gimnasio.Entities.Rutina", b =>
                {
                    b.HasOne("Gimnasio.Entities.Entrenador", "Entrenador")
                        .WithMany("Rutinas")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gimnasio.Entities.Socio", "Socio")
                        .WithMany("Rutinas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Gimnasio.Entities.RutinaEjercicio", b =>
                {
                    b.HasOne("Gimnasio.Entities.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gimnasio.Entities.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("Gimnasio.Entities.Socio", b =>
                {
                    b.HasOne("Gimnasio.Entities.User", "User")
                        .WithOne("Socio")
                        .HasForeignKey("Gimnasio.Entities.Socio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gimnasio.Entities.SocioEntrenador", b =>
                {
                    b.HasOne("Gimnasio.Entities.Entrenador", "Entrenador")
                        .WithMany("SocioEntrenadores")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gimnasio.Entities.Socio", "Socio")
                        .WithMany("SocioEntrenadores")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Gimnasio.Entities.SocioMembresia", b =>
                {
                    b.HasOne("Gimnasio.Entities.Membresia", "Membresia")
                        .WithMany("SocioMembresias")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gimnasio.Entities.Socio", "Socio")
                        .WithMany("SocioMembresias")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membresia");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Gimnasio.Entities.UserRole", b =>
                {
                    b.HasOne("Gimnasio.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gimnasio.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gimnasio.Entities.Ejercicio", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("Gimnasio.Entities.Entrenador", b =>
                {
                    b.Navigation("Rutinas");

                    b.Navigation("SocioEntrenadores");
                });

            modelBuilder.Entity("Gimnasio.Entities.Membresia", b =>
                {
                    b.Navigation("SocioMembresias");
                });

            modelBuilder.Entity("Gimnasio.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Gimnasio.Entities.Rutina", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("Gimnasio.Entities.Socio", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Rutinas");

                    b.Navigation("SocioEntrenadores");

                    b.Navigation("SocioMembresias");
                });

            modelBuilder.Entity("Gimnasio.Entities.User", b =>
                {
                    b.Navigation("AsistenciasRegistradas");

                    b.Navigation("Entrenador");

                    b.Navigation("Socio");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
